-- 코드를 입력하세요
SELECT T1.CART_ID
FROM CART_PRODUCTS AS T1
INNER JOIN (SELECT CART_ID, NAME FROM CART_PRODUCTS WHERE NAME ="Milk") AS T2
INNER JOIN (SELECT CART_ID, NAME FROM CART_PRODUCTS WHERE NAME ="Yogurt") AS T3
ON T1.CART_ID = T2.CART_ID AND T1.CART_ID = T3.CART_ID
GROUP BY 1
ORDER BY 1