-- 코드를 입력하세요
WITH RECURSIVE HOURS AS (
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM+1 FROM HOURS
    WHERE NUM<23
)

SELECT HOURS.NUM AS HOUR, COUNT(AO.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS AS AO
RIGHT JOIN HOURS ON EXTRACT(HOUR FROM AO.DATETIME) = HOURS.NUM
GROUP BY 1
ORDER BY 1


