-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, CONCAT(U.CITY," ",U.STREET_ADDRESS1," ",U.STREET_ADDRESS2) AS "전체주소", 
CONCAT(substr(U.TLNO,1,3),"-",substr(U.TLNO,4,4),"-",substr(U.TLNO,8,4)) AS "전화번호"
FROM USED_GOODS_BOARD AS B
INNER JOIN USED_GOODS_USER AS U
ON B.WRITER_ID = U.USER_ID
GROUP BY 1
HAVING COUNT(*) >= 3
ORDER BY 1 DESC