-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH, UI.GENDER, COUNT(DISTINCT UI.USER_ID) AS USERS
FROM USER_INFO AS UI
INNER JOIN ONLINE_SALE AS OS
ON UI.USER_ID = OS.USER_ID
GROUP BY 1,2,3
HAVING UI.GENDER IS NOT NULL
ORDER BY 1 ASC, 2 ASC, 3 ASC;