-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT AS A
INNER JOIN PATIENT AS P
INNER JOIN DOCTOR AS D
ON A.PT_NO = P.PT_NO AND A.MDDR_ID = D.DR_ID
WHERE A.MCDP_CD = "CS" AND A.APNT_CNCL_YN != "Y" AND DATE_FORMAT(A.APNT_YMD,"%Y-%m-%d") = "2022-04-13"
ORDER BY A.APNT_YMD ASC;