-- 코드를 입력하세요
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
ON C.CAR_ID = H.CAR_ID
WHERE DATE_FORMAT(H.START_DATE,"%Y-%m") = "2022-10"
AND C.CAR_TYPE = "세단"
GROUP BY C.CAR_ID
ORDER BY 1 DESC