-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/",T1.BOARD_ID,"/",T2.FILE_ID,T2.FILE_NAME,T2.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS T1
INNER JOIN USED_GOODS_FILE AS T2
INNER JOIN (SELECT BOARD_ID, MAX(VIEWS) AS MAX_VIEWS FROM USED_GOODS_BOARD) AS T3
ON T1.BOARD_ID = T2.BOARD_ID AND T1.VIEWS = T3.MAX_VIEWS
ORDER BY T2.FILE_ID DESC

# SELECT *
# FROM USED_GOODS_BOARD
# ORDER BY VIEWS DESC